# Generated by Django 5.1.2 on 2024-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='z',
            field=models.FloatField(default=0.0),
        ),
    ]
