# Generated by Django 5.1.2 on 2024-11-13 20:34

import service.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_message_normal_message_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='x',
        ),
        migrations.RemoveField(
            model_name='message',
            name='y',
        ),
        migrations.RemoveField(
            model_name='message',
            name='z',
        ),
        migrations.AlterField(
            model_name='message',
            name='normal',
            field=models.JSONField(default={'x': 0.0, 'y': 0.0, 'z': 0.0}, validators=[service.validators.VectorFieldValidator]),
        ),
        migrations.AlterField(
            model_name='message',
            name='position',
            field=models.JSONField(default={'x': 0.0, 'y': 0.0, 'z': 0.0}, validators=[service.validators.VectorFieldValidator]),
        ),
    ]
